site_name: Parisod Lab Dry Guide
theme: readthedocs
repo_url: https://github.com/parisodlab/dry-guide


markdown_extensions:
    - admonition
    - toc:
            permalink: true
            separator: _
    - fenced_code
    - sane_lists

nav:
    - Home: index.md
    - Lab Introduction: intro.md
    # - Best Practices: best_practices.md
    - Data Management:
          - Data Organization Guidelines: data-organization.md
          - Folder Organization Best Practices: best_practices.md
        #   - Data Backup: data-backup.md
        #   - Data Sharing: data-sharing.md
          - Data Submission on ENA: ena.md
          - Public Data Repositories: public-data.md
        #  - Data Submission on SRA: sra.md
    - IBU:
            - How to access: ibu-intro.md
        #     - Data on IBU: ibu-data.md
        #     - Snakemake: ibu-snakemake.md
            - Conda: ibu-conda.md
    - Coding Knowledge Base:
          - VScode: vscode.md
          - R: r.md
          - Command Line: bash.md
          - Source Control with Git and VScode: github.md
    - snakeGATK sequencing workflow:
            - Overview: pipeline-overview.md
        #     - QC pipeline: pipeline-readQC.md
            - Trim pipeline: pipeline-trimming.md
            - Alignment pipeline: pipeline-mapping.md
        #     - Genotyping pipeline: pipeline-GATK.md
        #     - Concordance pipeline: pipeline-concordance.md
        #     - Post-GATK pipeline: pipeline-postGATK.md
#     - Other pipelines:
#             - Freebayes calling: pipeline-freebayes.md
#     - snakeRNAseq workflow:
#             - Overview: rnaseq-overview.md
#             - Trim pipeline: rnaseq-trimming.md
#             - Alignment pipeline: rnaseq-alignment.md
#             - Counting pipeline: rnaseq-counting.md
#             - Differential expression pipeline: rnaseq-diffexp.md
#             - Visualization pipeline: rnaseq-visualization.md
#     - Quest:
#           - Introduction: quest-intro.md
#           - Data on b1059: b1059.md
#           - Nextflow: quest-nextflow.md
#           - Conda: quest-conda.md
#           - Docker: pipeline-docker.md
#           - GCP: pipeline-GCPconfig.md
#     - WI Sequencing pipelines:
#           - Overview: pipeline-overview.md
#           - trim-fq-nf: pipeline-trimming.md
#           - alignment-nf: pipeline-alignment.md
#           - wi-gatk: pipeline-wiGATK.md
#           - concordance-nf: pipeline-concordance.md
#           - post-gatk-nf: pipeline-postGATK.md
#           - imputation: pipeline-impute.md
#           - annotation-nf: pipeline-annotation-nf.md
#     - Other pipelines:
#           - NemaScan: pipeline-nemascan.md
#           - Image Analysis: pipeline-cellprofiler.md
#           - nil-ril-nf: pipeline-nil-ril.md
#           - genomes-nf: pipeline-genomes-nf.md
#           - cegwas2-nf: pipeline-cegwas.md
    - Other things:
#         - CeNDR: cendr.md
#         - Backup: backup.md
#     - Cloud: cloud.md
#     - Globus file sharing: sharing-globus.md
          - Parisod Labsite: labsite.md
# extra_css:
# - css/version-select.css
# extra_javascript:
# - js/version-select.js
